config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :kinous do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  root 'setumei#top'

  get 'setumei/top' => 'setumei#top'
  get 'setumei/about' => 'setumei#about'
  get 'setumei/seibun' => 'setumei#seibun'
  get 'setumei/kouka' => 'setumei#kouka'

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :kinou
end

app/models/kinou.rb
class Kinou < ApplicationRecord
mount_uploader :image, ImageUploader
belongs_to :user
has_many :likes, dependent: :destroy
has_many :liked_users, through: :likes, source: :user
has_many :comments, dependent: :destroy
has_many :kinou_tag_relations, dependent: :destroy
has_many :tags, through: :kinou_tag_relations, dependent: :destroy
end

app/models/kinou_tag_relation.rb
class KinouTagRelation < ApplicationRecord
  belongs_to :kinou
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :kinou
  belongs_to :user

  validates_uniqueness_of :kinou_id, scope: :user_id
end

app/models/tag.rb
class Tag < ApplicationRecord
    validates :name, presence: true
    #Tagsテーブルから中間テーブルに対する関連付け
    has_many :kinou_tag_relations, dependent: :destroy
    #Tagsテーブルから中間テーブルを介してArticleテーブルへの関連付け
    has_many :kinous, through: :kinou_tag_relations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :kinous, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_kinous, through: :likes, source: :kinou
  has_many :comments, dependent: :destroy

  validates :name, presence: true #追記
  validates :profile, length: { maximum: 200 }

  def already_liked?(kinou)
    self.likes.exists?(kinou_id: kinou.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
      # サインアップ時にnameのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      # アカウント編集の時にnameとprofileのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
      kinou = Kinou.find(params[:kinou_id])
      comment = kinou.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
      comment.user_id = current_user.id
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      end
    end
  
    private
  
      def comment_params
        params.require(:comment).permit(:content)
      end
end

app/controllers/kinous_controller.rb
class KinousController < ApplicationController
    before_action :authenticate_user!
    def index
      if params[:search] != nil && params[:search] != ''
        #部分検索かつ複数検索
        search = params[:search]
        @kinous = Kinou.where("name LIKE ? OR genre LIKE ?", "%#{search}%", "%#{search}%")
      else
        @kinous = Kinou.all
      end

      if params[:tag_ids]
        @kinous = []
        params[:tag_ids].each do |key, value|      
          @kinous += Tag.find_by(name: key).kinous if value == "1"
        end
        @kinous.uniq!
      end
 
      if params[:tag]
        Tag.create(name: params[:tag])
      end

    end

    

    def new
        @kinou = Kinou.new
    end
    
    def create
        kinou = Kinou.new(kinou_params)
        kinou.user_id = current_user.id
        if kinou.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
    end

    def show
        @kinou = Kinou.find(params[:id])
        @comments = @kinou.comments
        @comment = Comment.new
    end

    
    
    def edit
        @kinou = Kinou.find(params[:id])
    end

    def update
        kinou = Kinou.find(params[:id])
        if kinou.update(kinou_params)
          redirect_to :action => "show", :id => kinou.id
        else
          redirect_to :action => "new"
        end
    end

    def destroy
        kinou = Kinou.find(params[:id])
        kinou.destroy
        redirect_to action: :index
    end

    private
    def kinou_params
        params.require(:kinou).permit(:name, :genre, :about, :image, :age, :sex, :weight, :height, :frequency, :period, tag_ids: [])
    end


end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(kinou_id: params[:kinou_id]) 
        redirect_back(fallback_location: kinous_path)
      end
    
      def destroy
        like = Like.find_by(kinou_id: params[:kinou_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: kinous_path)
      end

end

app/controllers/setumei_controller.rb
class SetumeiController < ApplicationController

    def top
    end

    def about
    end

    def seibun
    end

    def kouka
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/kinous_helper.rb
module KinousHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/setumei_helper.rb
module SetumeiHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/kinous/edit.html.erb
<h1>機能性表示食品紹介</h1>
  <div class="box">
      <h2>編集ぺージ</h2>
  </div>
  <div class="box0">
    <p>編集したい情報を登録してください<br>
  </div>
  <p><hr class="sty"><br>

<%= form_for @kinou do |f| %>
  <div class="bo">
    <div class="box-11">
      <div class="field">
        <br>
        <h2>商品情報</h2>
        <br>
        <h4><%= f.label :商品名 %>(ex.ヤクルト1000)</h4>
        <p><%= f.text_field :name, :size => 30 %><br>
      </div>
    </div>
    <div class="box-11">
      <div class="field">
      <h4><%= f.label :機能性成分名  %>(ex.乳酸菌)</h4>
      <p><%= f.text_field :genre, :size => 30 %><br>
      </div>
    </div>
    <div class="box-11">
      <div class="field">
      <h4><%= f.label :商品の説明  %></h4>
      <p><%= f.text_area :about, :size => "50x10" %><br>
      </div>
    </div>
    <br>
  </div>
  <div class="bo">
    <div class="box-11">
      <div class="field">
        <br>
        <h4><%= f.label :商品の写真 %></h4>
        <p><%= f.file_field :image %>
      </div>
    </div>
    <div class="box-11">
      <h4>タグの選択</h4>
      <div class='form-group'>
      <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
        <div class='form-check'>
          <%= tag.label class: 'form-check-label' do %>
            <%= tag.check_box class: 'form-check-input' %>
            <%= tag.text %>
          <% end %>
        </div>
      <% end %>
      </div>
    </div>
    <br>
    <br>
  </div>
  <br><hr class="sty1"><br>

  <div class="bo-">
    <div class="box-11"> 
      <div class="field">
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <h2>投稿者情報</h2>
      <br>
      <h4><%= f.label :年齢  %></h4>
      <p><%= f.text_field :age, :size => 30 %>歳<br>
      </div>
    </div>
    <div class="box-11"> 
      <div class="field">
      <h4><%= f.label :性別  %></h4>
      <p><%= f.text_field :sex, :size => 30 %><br>
      </div>
    </div>
    <div class="box-11">
      <div class="field">
      <h4><%= f.label :体重 %></h4>
      <p><%= f.text_field :weight, :size => 30 %>kg<br>
      </div>
    </div>
    <div class="box-11">
      <div class="field">
      <h4><%= f.label :身長 %></h4>
      <p><%= f.text_field :height, :size => 30 %>cm<br>
      </div>
    </div>
    <div class="box-11">
      <div class="field">
      <h4><%= f.label :摂取頻度 %>(ex.１日２本)</h4>
      <p><%= f.text_field :frequency, :size => 30 %><br>
      </div>
    </div>
    <div class="box-11">
      <div class="field">
      <h4><%= f.label :摂取期間  %>(ex.8ケ月)</h4>
      <p><%= f.text_field :period, :size => 30 %><br>
      </div>
    </div>
    <br><hr class="sty"><br>
      <div class="box-2">
      <%= f.submit "編集する" %>　　　
      <%= link_to "一覧に戻る", kinous_path %>
    </div>
    <br>
  </div>
<% end %>
  
<br><hr class="sty2"><br>

app/views/kinous/index.html.erb
<h1>機能性表示食品紹介</h1>
<div class="box">
  <h2>投稿一覧ページ</h2>
</div>
<div class="box00">
  <%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
</div>
<div class="box-0">
  <%= link_to "トップページへ", root_path %>　　
  <%= link_to "新規投稿へ", new_kinou_path %>　　
  <% if user_signed_in? %>
    <%= link_to "マイページへ", user_path(current_user.id) %>
  <% end %>
</div>

<p><hr class="sty"><br>
<div class="bao">
  <div class="box-1">
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <h2>ユーザーの投稿を検索</h2>
    <br>
    <h5>・検索したい言葉を入力してください</h5>
    <%= form_tag({controller:"kinous",action:"index"}, method: :get) do %>
      <%= text_field_tag :search %>
      <%= submit_tag '検索する'  %>
    <% end %>
    <br><hr class="styleind"><br>
    <br>
    <h5>・検索したいタグを選択してください</h5>
    <%= form_tag({controller:"kinous",action:"index"}, method: :get) do %>
      <% Tag.all.each do |t| %>
          <li><%= check_box :tag_ids, t.name %><%= t.name %></li>
      <% end %>
      <%= submit_tag '検索' %>
    <% end %>
    <p>　<br>
    
  </div>
  <br>
  <br>
</div>
<p><hr class="sty"><br>


<div class="box000">
  <h2>ユーザーの投稿一覧</h2>
</div>

<div class="kinous-container">
  <% @kinous.each do |t| %>
    
    <div class="kinou">
      <div class="mainboxxx">
        <div class="mainboxx">
          
          <div class="boxx">
            <br>
            <h4><span class="p_underline4">　商品情報　</h4>
            <p><span class="p_u">商品名：</span><%= t.name %><br>
            <p><span class="p_u">機能性成分名：</span><%= t.genre %><br>
            <p><%= image_tag t.image_url, size: "300x250" if t.image? %><br>
            <% t.tags.each do |tag| %>
              <p><span class="p_u">健康効果タグ：</span><%= tag.name %><br>
            <% end %> 
          </div>
          
          
          <div class="boxxx">
            <br>
            <br>
            <h4><span class="p_underline4">　投稿者情報　</h4>
            <p><span class="p_u">投稿者名：</span><%= t.user.name %><br>
            <p><span class="p_u">年齢：</span><%= t.age %>歳<br>
            <p><span class="p_u">性別：</span><%= t.sex %><br>
            <p><span class="p_u">体重：</span><%= t.weight %>kg<br>
            <p><span class="p_u">身長：</span><%= t.height %>cm<br>
            <p><span class="p_u">商品の摂取頻度：</span><%= t.frequency %><br>
            <p><span class="p_u">商品の摂取期間：</span><%= t.period %><br>
          </div>
        </div>
      </div>
        <div class="main2">
          <div class="mainboxx2">
            <br>
            <p><span class="p_u">商品の説明：</span><%= t.about %><br>
            <br>
          </div>
        </div>
    </div>
    


    
      <div class="mainboxx3">
            <% if user_signed_in? %>
            <% if current_user.already_liked?(t) %>
                <%= button_to kinou_like_path(id: t.id, kinou_id: t.id), method: :delete do %>
                  <i class="fas fa-heart"></i><%= t.likes.count %>
                <% end %>
            <% else %>
                <%= button_to kinou_likes_path(id: t.id, kinou_id: t.id), method: :post do %>
                  <i class="fas fa-heart"></i><%= t.likes.count %>
                <% end %>
            <% end %>

            <% else %>
                <i class="fas fa-heart"></i><%= t.likes.count %>
            <% end %>
      </div>
      
    <div class="box-00">
        <%= link_to "詳細へ　", kinou_path(t.id) %>
        <% if user_signed_in? && current_user.id == t.user_id %>
            <%= link_to "編集する", edit_kinou_path(t.id) %>
    </div>
    <p><hr class="sty"><br>
    <div class="box-00">
        <%= button_to "削除する", kinou_path(t.id), method: :delete %>
        <br>
        <br>
        <% end %>
        </div>
        <% end %>
    </div>
    <p><hr class="styy"><br>
</div>

app/views/kinous/new.html.erb
<body>
  <h1>機能性表示食品紹介</h1>

  
  <div class="box">
    <h2>新規投稿ページ</h2>
  </div>
  <%= form_for @kinou do |f| %>

  <div class="box0">
    <p>紹介したい商品名や食品名、その他の情報を登録してください<br>
  </div>

  <p><hr class="sty"><br>
  <div class="bo">
    <div class="box-11">
      <div class="field">
        <br>
        <h2>商品情報</h2>
        <br>
        <h4><%= f.label :商品名 %>(ex.ヤクルト1000)</h4>
        <p><%= f.text_field :name, :size => 30 %><br>
      </div>
    </div>

    <div class="box-11">
      <div class="field">
      <h4><%= f.label :機能性成分名  %>(ex.乳酸菌)</h4>
      <p><span class="mida"><%= f.text_field :genre, :size => 30 %><br>
      </div>
    </div>

    <div class="box-11">
      <div class="field">
      <h4><%= f.label :商品の説明  %></h4>
      <p><%= f.text_area :about, :size => "50x10" %><br>
      </div>
    </div>
    <br>
  </div>
  <div class="bo">
    <div class="box-11">
      <div class="field">
      <br>
      <h4><%= f.label :商品の写真 %></h4>
      <p><%= f.file_field :image %><br>
      </div>
    </div>

    <div class="box-11">
      <h4>タグの選択</h4>
      <div class='form-group'>
      <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
          <div class='form-check'>
              <%= tag.label class: 'form-check-label' do %>
                  <%= tag.check_box class: 'form-check-input' %>
                  <%= tag.text %>
              <% end %>
          </div>
      <% end %>
      </div>
    </div>
    <br>
    <br>
  </div>
  <br><hr class="sty1"><br>

  <div class="bo-">
    <div class="box-11">
      <div class="field">
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <h2>投稿者情報</h2>
      <br>
      <h4><%= f.label :年齢  %></h4>
      <p><%= f.text_field :age, :size => 30 %>歳<br>
      </div>
    </div>

    <div class="box-11">
      <div class="field">
      <h4><%= f.label :性別  %></h4>
      <p><%= f.text_field :sex, :size => 30 %><br>
      </div>
    </div>

    <div class="box-11">
      <div class="field">
      <h4><%= f.label :体重 %></h4>
      <p><%= f.text_field :weight, :size => 30 %>kg<br>
      </div>
    </div>

    <div class="box-11">
      <div class="field">
      <h4><%= f.label :身長 %></h4>
      <p><%= f.text_field :height, :size => 30 %>cm<br>
      </div>
    </div>

    <div class="box-11">
      <div class="field">
      <h4><%= f.label :摂取頻度 %>(ex.１日２本)</h4>
      <p><%= f.text_field :frequency, :size => 30 %><br>
      </div>
    </div>

    <div class="box-11">
      <div class="field">
      <h4><%= f.label :摂取期間  %>(ex.8ケ月)</h4>
      <p><%= f.text_field :period, :size => 30 %><br>
      </div>
    </div>
    
  
    <br><hr class="styyy"><br>

    <div class="box-2">
      <%= f.submit "投稿する" %>　　　
      <% end %>
      <%= link_to "投稿一覧へ", kinous_path %>
    </div>
    <br>
  </div>
  <br><hr class="sty2"><br>
</body>

app/views/kinous/show.html.erb
<h1>機能性表示食品紹介</h1>
<div class="box">
  <h2>投稿詳細ページ</h2>
</div>
<p><hr class="sty"><br>
<div class="kinou">
  <div class="mainboxxx">
    <div class="mainboxx">
      <div class="boxx">
        <br>
        <h4><span class="p_underline4">　商品情報　</h4>
        <p><span class="p_u">商品名：</span><%= @kinou.name %></p>
        <p><span class="p_u">機能性成分名：</span><%= @kinou.genre %></p>
        <p><%= image_tag @kinou.image_url, size: "300x250" if @kinou.image? %></p>
        <% @kinou.tags.each do |tag| %>
          <p><span class="p_u">健康効果タグ：</span><%= tag.name %><br>
        <% end %>
      </div>
      <div class="boxxx">
        <br>
        <br>
        <h4><span class="p_underline4">　投稿者情報　</h4>
        <p><span class="p_u">投稿者名：</span><%= @kinou.user.name %><br>
        <p><span class="p_u">年齢：</span><%= @kinou.age %>歳</p>
        <p><span class="p_u">性別：</span><%= @kinou.sex %></p>
        <p><span class="p_u">体重：</span><%= @kinou.weight %>kg</p>
        <p><span class="p_u">身長：</span><%= @kinou.height %>cm</p>
        <p><span class="p_u">商品の摂取頻度：</span><%= @kinou.frequency %></p>
        <p><span class="p_u">商品の摂取期間：</span><%= @kinou.period %></p>
      </div>
    </div>
  </div>
  <div class="main2">
    <div class="mainboxx2">
      <br>
      <p><span class="p_u">商品の説明：</span><%= @kinou.about %></p>
      <br>
    </div>
  </div>
  
</div>


<div class="mainboxx3">
  <% if user_signed_in? %>
        <% if current_user.already_liked?(@kinou) %>
          <%= button_to kinou_like_path(@kinou), method: :delete do %>
            <i class="fas fa-heart"></i><%= @kinou.likes.count %>
          <% end %>
        <% else %>
          <%= button_to kinou_likes_path(@kinou), method: :post do %>
            <i class="far fa-heart"></i><%= @kinou.likes.count %>
          <% end %>
        <% end %>
      <% else %>
      <i class="far fa-heart"></i><%= @kinou.likes.count %>
      <% end %>
    <%= link_to "編集する", edit_kinou_path(@kinou.id) %>
  </div>
</div>
<p><hr class="sty"><br>

<div class="box--11">
  <h3>＜いいねしたユーザー＞</h3>
  <% @kinou.liked_users.each do |user| %>
    <li><%= user.name %></li>
  <% end %>
</div>
<p><hr class="sty1"><br>
<div class="box--11">
  <div class="comment-wrapper">
  <h3>＜コメント一覧＞</h3>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.name unless c.user.blank? %>：
      <%= c.content %>
    </div>
  <% end %>
</div>
<br>
<div class="box--11">
  <h5>下記フォームからコメントを投稿できます</h5>
    <% if user_signed_in? %>
      <%= form_with(model: [@kinou, @comment], local: true) do |f| %>
        <%= f.text_area :content %>
        <%= button_tag type: "submit" do %>
          <h5><i class="far fa-comments"></i> 
          コメントする</h5>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>
<p><hr class="sty"><br>
<div class="mainboxx3">
 <%= link_to "一覧に戻る", kinous_path %>
</div>
<p><hr class="sty2"><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tokuho</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/1a4bdf9190.js" crossorigin="anonymous"></script>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1> </h1>
      <div class="header-list">
      <ul>
        <%= link_to "ホーム", root_path %>
        <%= link_to "ログイン", kinous_path %>
        <%= link_to "新規登録", new_user_registration_path %>
        <%= link_to "新規投稿",new_kinou_path %>
      </ul>
      </div>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
      <div class="aaa">
      <div class="footer-list">
        KINOUS
        </div>
      <div class="contents">
        <div class="bbb">
          <h5>HOME</h5>
          <h3><span class="p_underline"><%= link_to "トップページ　　　　　　　　　　　　　　　　　　　　　　　　　　　›", root_path %>
          </h3>
        </div>
        <div class="bbb">
          <h5>ABOUT</h5>
          <h3><span class="p_underline"><%= link_to "サイトの想い　　　　　　　　　　　　　　　　　　　　　　　　　　　›", setumei_about_path %></h3>
        </div>
        <div class="bbb">
          <h5>MAIN CONTENTS</h5>
          <h3>
          <%= link_to "健康機能を担う成分　　　　　　　　　　　　　　　　　　　　　　　　›", setumei_seibun_path %><br>
          <%= link_to "健康効果一覧　　　　　　　　　　　　　　　　　　　　　　　　　　　›", setumei_kouka_path %><br>
          <span class="p_underline"><%= link_to "機能性成分を含む製品レビュー　　　　　　　　　　　　　　　　　　　›", kinous_path %></h3>
        </div>
        <br><hr class="style1"><br>
      </div>
    </footer>
  

  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>